#!/usr/bin/env bash
# chmod +x build
# docker build -f app/Dockerfile -t acaty/test:latest ./app
# docker system prune -f
# docker build -f Dockerfile -t acaty/test:dusk --no-cache .
docker build -f Dockerfile -t acaty/test:dusk .