# docker-compose.yml (corregido)

version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: acaty/test:latest
    volumes:
      - ./:/var/www/html:rw
    ports:
      - "${APP_PORT:-8080}:80"
      - "6001:6001"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - stydenet

  mysql:
    container_name: mysql
    image: mysql:8.0
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${DB_DATABASE:-laravel}"
      MYSQL_USER: "${DB_USER:-laravel}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      TZ: "America/Lima"
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stydenet

networks:
  stydenet:
    driver: bridge

volumes:
  mysqldata:
  # redisdata:
  #   driver: local
